// <auto-generated />
using CityTraffic.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityTraffic.DAL.Migrations
{
    [DbContext(typeof(CityTrafficDB))]
    [Migration("20240217171217_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("CityTraffic.Models.Entities.EntityStoppoint", b =>
                {
                    b.Property<int>("StoppointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("stoppoint_id");

                    b.Property<bool>("FavoriteStoppoint")
                        .HasColumnType("INTEGER")
                        .HasColumnName("favorite_stoppoint");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("StoppointName")
                        .HasColumnType("TEXT")
                        .HasColumnName("stoppoint_name");

                    b.HasKey("StoppointId");

                    b.ToTable("Stoppoints");
                });

            modelBuilder.Entity("CityTraffic.Models.Entities.EntityTransportRoute", b =>
                {
                    b.Property<string>("RouteId")
                        .HasColumnType("TEXT")
                        .HasColumnName("route_id");

                    b.Property<bool>("FavoriteTransportRoute")
                        .HasColumnType("INTEGER")
                        .HasColumnName("favorite_transport_route");

                    b.Property<string>("RouteNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("route_number");

                    b.Property<int>("RouteTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("route_type_id");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("RouteId");

                    b.ToTable("TransportRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
