// <auto-generated />
using CityTraffic.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityTraffic.DAL.Migrations
{
    [DbContext(typeof(CityTrafficDB))]
    partial class CityTrafficDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("CityTraffic.Models.Entities.Stoppoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Favorites")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoppointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoppointName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stoppoints");
                });

            modelBuilder.Entity("CityTraffic.Models.Entities.TransportRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Favorites")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RouteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("RouteTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TransportRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
